### ISSUE TITLE
Popover is not hidden when state changes

### ISSUE THREAD

**Issue by hmartos** [rubenv/angular-rt-popup#18]
The problem is that popover is not hidden when state changes (I am using ui-router, but I suppose it will also happen when using ngRoute).
For example, I open my popup by pressing a help button showing some info to a user, and if I doesn't close the popup by clicking the close button or clicking in any other place in the screen  and I click in my menu performing a state change, the popup remains in the screen in the new state. 

Thank you!

**Comment by Kukunin** [comment]
:+1:

**Comment by rubenv** [comment]
Here's something you can add to your application right now:

``` js
$rootScope.$on("$stateChangeStart", function () {
    Popup.close();
});
```

**Comment by hmartos** [comment]
Works perfectly, thank you!! 
Just remember that you must include Popup factory in the run method to have this code working.
